[workspace]
resolver = "2"
members = [
  "das_api",
  "digital_asset_types",
  "metaplex-rpc-proxy",
  "migration",
  "nft_ingester",
  "tools/acc_forwarder",
  "tools/bgtask_creator",
  "tools/fetch_trees",
  "tools/load_generation",
  "tools/tree-status",
  "tools/txn_forwarder",
]

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"

[profile.release]
lto = true
codegen-units = 1
