[workspace]
resolver = "2"
members = [
  "das_api",
  "digital_asset_types",
  "metaplex-rpc-proxy",
  "migration",
  "nft_ingester",
  "nft_ingester2",
  "program_transformers",
  "tools/acc_forwarder",
  "tools/bgtask_creator",
  "tools/fetch_trees",
  "tools/load_generation",
  "tools/tree-status",
  "tools/txn_forwarder",
]

[workspace.package]
version = "0.7.2"
edition = "2021"
repository = "https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure"
publish = false

[workspace.dependencies]
anchor-client = "0.28.0"
anchor-lang = "0.28.0"
anyhow = "1.0.75"
async-std = "1.0.0"
async-stream = "0.3.5"
async-trait = "0.1.60"
atty = "0.2.14"
blockbuster = "0.9.0-beta.1"
borsh = "~0.10.3"
bs58 = "0.4.0"
cadence = "0.29.0"
cadence-macros = "0.29.0"
cargo-lock = "9.0.0"
chrono = "0.4.19"
clap = "4.2.2"
digital_asset_types = { path = "digital_asset_types" }
enum-iterator = "1.2.0"
env_logger = "0.10.0"
figment = "0.10.8"
flatbuffers = "23.1.21"
futures = "0.3.28"
git-version = "0.3.5"
hex = "0.4.3"
hyper = "0.14.23"
indexmap = "1.9.3"
json5 = "0.4.1"
jsonpath_lib = "0.3.0"
jsonrpsee = "0.16.2"
lazy_static = "1.4.0"
log = "0.4.17"
mime_guess = "2.0.4"
mpl-bubblegum = "1.0.1-beta.3"
mpl-token-metadata = "=2.0.0-beta.1"
nft_ingester = { path = "nft_ingester" }
num-traits = "0.2.15"
open-rpc-derive = "0.0.4"
open-rpc-schema = "0.0.4"
opentelemetry = "0.21.0"
opentelemetry-jaeger = "0.20.0"
opentelemetry_sdk = "0.21.1"
plerkle_messenger = "1.6.0"
plerkle_serialization = "1.6.0"
program_transformers = { path = "program_transformers" }
prometheus = "0.13.3"
proxy-wasm = "0.2.0"
rand = "0.8.5"
redis = "0.22.3"
regex = "1.6.0"
reqwest = "0.11.13"
rust-crypto = "0.2.36"
schemars = "0.8.6"
schemars_derive = "0.8.6"
sea-orm = "0.10.6"
sea-orm-migration = "0.10.6"
sea-query = "0.28.1"
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.9.27"
solana-account-decoder = "=1.16.19"
solana-client = "=1.16.19"
solana-program = "=1.16.19"
solana-sdk = "=1.16.19"
solana-transaction-status = "=1.16.19"
spl-account-compression = "0.2.0"
spl-associated-token-account = ">= 1.1.3, < 3.0"
spl-concurrent-merkle-tree = "0.2.0"
spl-noop = "0.2.0"
spl-token = ">= 3.5.0, < 5.0"
sqlx = "0.6.2"
stretto = "0.7.2"
thiserror = "1.0.31"
tokio = "1.30.0"
tokio-stream = "0.1.14"
tower = "0.4.13"
tower-http = "0.3.5"
tracing = "0.1.35"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.16"
txn_forwarder = { path = "tools/txn_forwarder" }
url = "2.3.1"
vergen = "8.2.1"
yellowstone-grpc-client = { git = "https://github.com/rpcpool/yellowstone-grpc.git", branch = "1.16-proto-convert-from" } # TODO: use tag, when branch merged
yellowstone-grpc-proto = { git = "https://github.com/rpcpool/yellowstone-grpc.git", branch = "1.16-proto-convert-from" } # TODO: use tag, when branch merged
yellowstone-grpc-tools = { git = "https://github.com/rpcpool/yellowstone-grpc.git", branch = "1.16-proto-convert-from", default-features = false } # TODO: use tag, when branch merged

[patch.crates-io]
blockbuster = { git = "https://github.com/rpcpool/blockbuster.git", tag = "blockbuster-rm-plerkle-v0.9.0-beta.1" }

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"

[profile.release]
lto = true
codegen-units = 1
