[workspace]
members = [
  "digital_asset_types",
  "metaplex-rpc-proxy",
  "migration",
  "nft_ingester",
  "tools/acc_forwarder",
  "tools/bgtask_creator",
  "tools/fetch_trees",
  "tools/load_generation",
  "tools/tree-status",
  "tools/txn_forwarder",
]
exclude = [
  "das_api",
]

[profile.release]
lto = true
codegen-units = 1
