[package]
name = "metaplex-rpc-proxy"
version = "0.6.8"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.0"
wasm-bindgen = "0.2.83"
lazy_static = "1.4.0"
regex = "1.6.0"
log = "0.4.17"
wasi = "0.7.0"
